FROM ghcr.io/linuxserver/baseimage-kasmvnc:arch

LABEL org.opencontainers.image.title="Arch Linux Webtop with KASMVNC"
LABEL org.opencontainers.image.source="https://github.com/zyrakq/arch-devcontainer-images"
LABEL org.opencontainers.image.description="Arch Linux webtop image with KASMVNC desktop environment"
LABEL org.opencontainers.image.licenses="GPL-3.0"
LABEL org.opencontainers.image.authors="Zyrakq <serg.shehov@tutanota.com>"
