FROM lscr.io/linuxserver/webtop:arch-kde

LABEL org.opencontainers.image.title="Arch Linux Webtop with KDE, Docker-in-Docker, Node.js and .NET"
LABEL org.opencontainers.image.source="https://github.com/zyrakq/arch-devcontainer-images"
LABEL org.opencontainers.image.description="Arch Linux webtop image with KDE, Docker-in-Docker, Node.js and .NET"
LABEL org.opencontainers.image.licenses="MIT OR Apache-2.0"
