FROM lscr.io/linuxserver/webtop:arch-i3

LABEL org.opencontainers.image.title="Arch Linux Webtop with I3"
LABEL org.opencontainers.image.source="https://github.com/zyrakq/arch-devcontainer-images"
LABEL org.opencontainers.image.description="Arch Linux webtop image with I3 desktop environment"
LABEL org.opencontainers.image.licenses="GPL-3.0"
LABEL org.opencontainers.image.authors="Zyrakq <serg.shehov@tutanota.com>"
