FROM lscr.io/linuxserver/webtop:arch-xfce

LABEL org.opencontainers.image.title="Arch Linux Webtop with XFCE"
LABEL org.opencontainers.image.source="https://github.com/zyrakq/arch-devcontainer-images"
LABEL org.opencontainers.image.description="Arch Linux webtop image with XFCE desktop environment"
LABEL org.opencontainers.image.licenses="GPL-3.0"
LABEL org.opencontainers.image.authors="Zyrakq <serg.shehov@tutanota.com>"
