FROM lscr.io/linuxserver/webtop:arch-xfce

LABEL org.opencontainers.image.title="Arch Linux Webtop with XFCE, Docker-outside-of-Docker and Rust"
LABEL org.opencontainers.image.source="https://github.com/zyrakq/arch-devcontainer-images"
LABEL org.opencontainers.image.description="Arch Linux webtop image with XFCE, Docker-outside-of-Docker and Rust"
LABEL org.opencontainers.image.licenses="MIT OR Apache-2.0"
