FROM ghcr.io/linuxserver/baseimage-kasmvnc:arch

LABEL org.opencontainers.image.title="Arch Linux Webtop with KASMVNC, Docker-in-Docker and Go"
LABEL org.opencontainers.image.source="https://github.com/zyrakq/arch-devcontainer-images"
LABEL org.opencontainers.image.description="Arch Linux webtop image with KASMVNC, Docker-in-Docker and Go"
LABEL org.opencontainers.image.licenses="MIT OR Apache-2.0"
