FROM lscr.io/linuxserver/webtop:arch-mate

LABEL org.opencontainers.image.title="Arch Linux Webtop with MATE, Docker-outside-of-Docker and Node.js"
LABEL org.opencontainers.image.source="https://github.com/zyrakq/arch-devcontainer-images"
LABEL org.opencontainers.image.description="Arch Linux webtop image with MATE, Docker-outside-of-Docker and Node.js"
LABEL org.opencontainers.image.licenses="MIT OR Apache-2.0"
