name: Cleanup Old Images

on:
  workflow_dispatch:
    inputs:
      keep_count:
        description: 'Number of recent versions to keep'
        required: false
        default: '10'
        type: string
  schedule:
    - cron: "0 3 * * 0"

jobs:
  cleanup:
    name: Cleanup ${{ matrix.image }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - arch-base
          - arch-base-common
    
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.image }}
          package-type: 'container'
          min-versions-to-keep: ${{ inputs.keep_count || '10' }}
          delete-only-untagged-versions: 'false'